melodies = [
       "チャイム3B7",
    "チャイム3B6",
    "JR-SH5-1",
    "JR-SH1-1",
    "JR-SH8-1",
    "JR-SH3-1",
    "JR-SH3-3",
    "JR-SH9-3",
    "JR-SH4-1",
    "JR-SH7-1",
    "JR-SH6-1",
    "ホリデイV2",
    "ホリデイV1",
    "あざみ野V1",
    "くるみあそび",
    "sunrise鐘強調",
    "メロディーV1",
    "シンコペーション",
    "sunny islands",
    "dance on",
    "雪解け間近V1",
    "花のほころびV2",
    "瞬く街並みV1",
    "星空の下",
    "公園の楓",
    "公園通り",
    "九月の風V1",
    "ドリームタイム",
    "緑の車窓",
    "海辺の散歩",
    "ジュピターVer.B",
    "ドリームパーク",
    "春だより",
    "夢のワルツ",
    "森の妖精",
    "朝つゆ",
    "旅の予感",
    "田園浪漫",
    "高原のつぶやき",
    "淡い恋心",
    "青空と線路",
    "ジュピターVer.G",
    "通勤ステップ",
    "ハッピーガール",
    "朝のドヴィッシー",
    "ジュピターVer.E",
    "幸福の銀レール",
    "蝶",
    "木もれ陽の散歩道",
    "おはよう",
    "トレイントレイン",
    "JR-SHR4-1",
    "JR-SHR8-3",
    "SF10-38",
    "SF10-43",
    "夏色の時間V1",
    "小川のせせらぎV2",
    "新たな季節",
    "原宿a",
    "原宿b",
    "陽だまりV4",
    "チャイム3B1",
    "チャイム3B5",
    "ML-24",
    "カリフォルニアシャワーVer.A",
    "カリフォルニアシャワーVer.B",
    "JupiterVer.A",
    "JupiterVer.B",
    "JupiterVer.C",
    "線路は続くよどこまでもVer.A",
    "線路は続くよどこまでもVer.B",
    "線路は続くよどこまでもVer.C",
    "ナンバーワン野郎！Ver.A",
    "ナンバーワン野郎！Ver.B",
    "FRONTALE2000",
    "FRONTALE20000",
    "すいみん不足",
    "夢をかなえてドラえもん",
    "ぼくドラえもん",
    "きてよパーマン",
    "ドラえもんのうた",
    "丘を越えてVer.A",
    "丘を越えてVer.B",
    "すみれの花咲く頃(矢板Ver.)",
    "浜千鳥(矢板Ver.)",
    "春風V1",
    "陽だまりV1",
    "春風V2",
    "浜千鳥(高速Ver.)",
    "稲城繁盛節Ver.A",
    "稲城繁盛節Ver.B",
    "川崎市歌Ver.A",
    "川崎市歌Ver.B",
    "木々の目覚めV2",
    "輝く未来",
    "Let It Go 〜ありのままで〜",
    "鉄道唱歌Ver.B",
    "鉄道唱歌Ver.C",
    "遊園地のある駅",
    "四季〜春 第一楽章〜",
    "四季〜秋 第三楽章〜",
    "JR-SH2-1"
]

formatted_melodies = []

for melody in melodies:
    entry = {
        "company": "JR東日本",
        "line": "未使用",
        "station": "未使用",
        "melody": melody,
        "file": f"audio/{melody.replace(' ', '')}.mp3"
    }
    formatted_melodies.append(entry)

# Print JSON-like output
import json
print(json.dumps(formatted_melodies, ensure_ascii=False, indent=2))
