name: Update daily counter

on:
  schedule:
    # every day at 00:10 UTC (adjust as needed).  "cron" uses UTC.
    - cron: '10 0 * * *'
  workflow_dispatch: {} # manual trigger if needed

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps (if any)
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Run updateDailyCounter
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          node updateDailyCounter.js